### ISSUE TITLE
telegraf config rendering fails if the entry has no attributes

### ISSUE THREAD

**Issue by rob42** [jamescarr/ansible-role-telegraf#9]
Using ubuntu 16.04. Ansible 2.2. 
While rendering the telegraf.conf the following fails:

```
plugins:
  outputs:
    influxdb:
      urls: ['{{influxdb_host_url}}']
      database: "telegraf"
      username: "telegraf"
      password: "{{ influxdb_telegraf_password }}"
  inputs:
    # Read metrics about cpu usage
    cpu:
      percpu: true
      totalcpu: true
      collect_cpu_time: false
   diskio:
   kernel:
```
Gets 'not iterable' error
The following works ok
```
plugins:
  outputs:
    influxdb:
      urls: ['{{influxdb_host_url}}']
      database: "telegraf"
      username: "telegraf"
      password: "{{ influxdb_telegraf_password }}"
  inputs:
    # Read metrics about cpu usage
    cpu:
      percpu: true
      totalcpu: true
      collect_cpu_time: false
   #diskio:
   #kernel:
```
Do I need to add a dummy attribute, or [] or something?
